User repository
EntryDSM/Gucci pull request #7
Opened 2019-04-26 02:11 UTC by Joonmo-dev

2019-05-22 12:38 UTC, taemin-fp commented on src/config.ts
> +export const mongodbName = 'gucci';
상수 이름은 `UPPER_CASE`로 하는 게 어떨까요

2019-05-22 12:38 UTC, taemin-fp commented on src/repositories/UserRepository.ts
> +export class InmemoryUserRepository implements UserRepository {
Inmemory라고 되어 있는데, MongoDB를 사용하는 것 같네요!

2019-05-22 12:38 UTC, taemin-fp commented on src/repositories/UserRepository.ts
> +    const result: InsertOneWriteOpResult = await this.collection.insertOne(
`const { result }`로 빼면 `return`할 때 편하다고 생각해요.

2019-05-22 12:38 UTC, taemin-fp commented on src/repositories/UserRepository.ts
> +    return await this.collection.findOne({ username });
에러가 throw되면 catch해서 적절한 처리를 해야 할 것으로 보여요~ (참조: http://mongodb.github.io/node-mongodb-native/3.2/api/Collection.html#~resultCallback)

2019-05-22 23:58 UTC, engolder commented on src/repositories/UserRepository.ts
> +export class InmemoryUserRepository implements UserRepository {
무슨뜻이죠?? 어떤 부분이 잘못된건지 모르겠어요

2019-05-23 02:08 UTC, HubCodes commented on src/repositories/UserRepository.ts
> +export class InmemoryUserRepository implements UserRepository {
MongoDB를 쓰는데 이름이 Inmemory인 이유를 모르겠어요~

2019-05-23 02:10 UTC, engolder commented on src/repositories/UserRepository.ts
> +export class InmemoryUserRepository implements UserRepository {
이런식으로 구현하는것이 아닌가요? 잘 모르겠습니다. 혹시 링크가 있으면 보내주세요

2019-06-14 07:13 UTC, rscarrera27 requested changes
테스트

2019-06-14 07:41 UTC, rscarrera27 approved these changes

2019-06-18 00:13 UTC, closed without merging